<?php


    namespace blackpanda\ibs;

    use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
    class IBSngEventServiceProvider extends ServiceProvider
    {
        public function boot()
        {
            parent::boot(); // TODO: Change the autogenerated stub
        }
    }
